use_frameworks!
inhibit_all_warnings!

target 'VZKit_Tests' do
  pod 'VZKit', :path => '../'
  pod 'AFNetworking', '~>3.1.0'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'MJExtension', '~> 3.0.13'
  pod 'ReactiveObjC', '~> 3.0.0'
  pod 'Masonry', '~> 1.0.2'
  pod 'DZNEmptyDataSet', '~> 1.8.1'
  pod 'FMDB', '~> 2.7.2'
end
